# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='county',
            new_name='country',
        ),
    ]
